/*******************************************************************************
 * Copyright © 2015 Hoffmann-La Roche
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package com.emc.d2fs.schemas.models;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 * 
 */
public class ModelPortService extends Service {

	private final static QName MODELPORTSERVICE_QNAME = new QName("http://www.emc.com/d2fs/schemas/models", "ModelPortService");

	public ModelPortService(URL wsdlLocation) {
		super(wsdlLocation, MODELPORTSERVICE_QNAME);
	}

	public ModelPortService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	/**
	 * 
	 * @return returns ModelPort
	 */
	@WebEndpoint(name = "ModelPortSoap11")
	public ModelPort getModelPortSoap11() {
		return super.getPort(new QName("http://www.emc.com/d2fs/schemas/models", "ModelPortSoap11"), ModelPort.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default values.
	 * @return returns ModelPort
	 */
	@WebEndpoint(name = "ModelPortSoap11")
	public ModelPort getModelPortSoap11(WebServiceFeature... features) {
		return super.getPort(new QName("http://www.emc.com/d2fs/schemas/models", "ModelPortSoap11"), ModelPort.class, features);
	}

}
